// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

type Queries struct{ db *pgxpool.Pool }

func New(db *pgxpool.Pool) *Queries { return &Queries{db: db} }

type CreateAgentParams struct {
	ID       string
	Name     string
	Endpoint string
	Status   string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, `INSERT INTO agents (id, name, endpoint, status) VALUES ($1, $2, $3, $4) RETURNING id, name, endpoint, status, created_at, updated_at`, arg.ID, arg.Name, arg.Endpoint, arg.Status)
	var item Agent
	err := row.Scan(&item.ID, &item.Name, &item.Endpoint, &item.Status, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}

func (q *Queries) GetAgentByID(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, `SELECT id, name, endpoint, status, created_at, updated_at FROM agents WHERE id = $1`, id)
	var item Agent
	err := row.Scan(&item.ID, &item.Name, &item.Endpoint, &item.Status, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, `SELECT id, name, endpoint, status, created_at, updated_at FROM agents ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var item Agent
		if err := rows.Scan(&item.ID, &item.Name, &item.Endpoint, &item.Status, &item.CreatedAt, &item.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
