// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "context"

func (q *Queries) CreateHeartbeat(ctx context.Context, agentID string) (Heartbeat, error) {
	row := q.db.QueryRow(ctx, `INSERT INTO heartbeats (agent_id) VALUES ($1) RETURNING id, agent_id, created_at`, agentID)
	var item Heartbeat
	err := row.Scan(&item.ID, &item.AgentID, &item.CreatedAt)
	return item, err
}
