// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"
)

type JobEvent struct {
	ID        int64
	JobID     string
	Type      string
	Message   string
	CreatedAt time.Time
}

func (q *Queries) CreateJobEvent(ctx context.Context, jobID, eventType, message string) (JobEvent, error) {
	row := q.db.QueryRow(ctx, `INSERT INTO job_events (job_id, type, message) VALUES ($1, $2, $3) RETURNING id, job_id, type, message, created_at`, jobID, eventType, message)
	var item JobEvent
	err := row.Scan(&item.ID, &item.JobID, &item.Type, &item.Message, &item.CreatedAt)
	return item, err
}
