// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"
)

type Job struct {
	ID        string
	Type      string
	Payload   []byte
	Status    string
	AgentID   *string
	Progress  int
	Result    []byte
	Error     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateJobParams struct {
	ID      string
	Type    string
	Payload []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, `INSERT INTO jobs (id, type, payload, status) VALUES ($1, $2, $3, 'pending') RETURNING id, type, payload, status, agent_id, progress, result, error, created_at, updated_at`, arg.ID, arg.Type, arg.Payload)
	var item Job
	err := row.Scan(&item.ID, &item.Type, &item.Payload, &item.Status, &item.AgentID, &item.Progress, &item.Result, &item.Error, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}

func (q *Queries) AssignNextJob(ctx context.Context, agentID string) (Job, error) {
	row := q.db.QueryRow(ctx, `UPDATE jobs SET status = 'in_progress', agent_id = $1, updated_at = NOW() WHERE id = (SELECT id FROM jobs WHERE status = 'pending' ORDER BY created_at ASC FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, type, payload, status, agent_id, progress, result, error, created_at, updated_at`, agentID)
	var item Job
	err := row.Scan(&item.ID, &item.Type, &item.Payload, &item.Status, &item.AgentID, &item.Progress, &item.Result, &item.Error, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}

func (q *Queries) UpdateJobProgress(ctx context.Context, id string, progress int) (Job, error) {
	row := q.db.QueryRow(ctx, `UPDATE jobs SET progress = $2, updated_at = NOW() WHERE id = $1 AND status = 'in_progress' RETURNING id, type, payload, status, agent_id, progress, result, error, created_at, updated_at`, id, progress)
	var item Job
	err := row.Scan(&item.ID, &item.Type, &item.Payload, &item.Status, &item.AgentID, &item.Progress, &item.Result, &item.Error, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}
func (q *Queries) CompleteJob(ctx context.Context, id string, result []byte) (Job, error) {
	row := q.db.QueryRow(ctx, `UPDATE jobs SET status = 'completed', progress = 100, result = $2, updated_at = NOW() WHERE id = $1 AND status = 'in_progress' RETURNING id, type, payload, status, agent_id, progress, result, error, created_at, updated_at`, id, result)
	var item Job
	err := row.Scan(&item.ID, &item.Type, &item.Payload, &item.Status, &item.AgentID, &item.Progress, &item.Result, &item.Error, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}
func (q *Queries) FailJob(ctx context.Context, id string, message string) (Job, error) {
	row := q.db.QueryRow(ctx, `UPDATE jobs SET status = 'failed', error = $2, updated_at = NOW() WHERE id = $1 AND status = 'in_progress' RETURNING id, type, payload, status, agent_id, progress, result, error, created_at, updated_at`, id, message)
	var item Job
	err := row.Scan(&item.ID, &item.Type, &item.Payload, &item.Status, &item.AgentID, &item.Progress, &item.Result, &item.Error, &item.CreatedAt, &item.UpdatedAt)
	return item, err
}
