// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "time"

type Agent struct {
	ID        string
	Name      string
	Endpoint  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
