// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "time"

type Agent struct {
	ID        string
	Name      string
	Endpoint  string
	Status    string
	TokenHash []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	LastSeen  *time.Time
}

type Heartbeat struct {
	ID        int64
	AgentID   string
	CreatedAt time.Time
}
